language: ruby
rvm:
  - 2.4.1

before_install:
  - nvm install node@10

install:
  - npm install
  - bundle install

before_script:
 - chmod +x ./script/cibuild
 - chmod +x ./script/push.sh

script:
 - ./script/cibuild
 - ./script/push.sh

sudo: false # route your build to the container-based infrastructure for a faster build

cache:
  bundler: true # caching bundler gem packages will speed up build
  directories:
      - node_modules

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false